import type { Locale } from "@/lib/i18n";

/** Indonesian names (Alkitab) keyed by canonical English book name from bible-data. */
export const BOOK_NAME_ID: Record<string, string> = {
  Genesis: "Kejadian",
  Exodus: "Keluaran",
  Leviticus: "Imamat",
  Numbers: "Bilangan",
  Deuteronomy: "Ulangan",
  Joshua: "Yosua",
  Judges: "Hakim-hakim",
  Ruth: "Rut",
  "1 Samuel": "1 Samuel",
  "2 Samuel": "2 Samuel",
  "1 Kings": "1 Raja-raja",
  "2 Kings": "2 Raja-raja",
  "1 Chronicles": "1 Tawarikh",
  "2 Chronicles": "2 Tawarikh",
  Ezra: "Ezra",
  Nehemiah: "Nehemia",
  Esther: "Ester",
  Job: "Ayub",
  Psalms: "Mazmur",
  Proverbs: "Amsal",
  Ecclesiastes: "Pengkhotbah",
  "Song of Solomon": "Kidung Agung",
  Isaiah: "Yesaya",
  Jeremiah: "Yeremia",
  Lamentations: "Ratapan",
  Ezekiel: "Yehezkiel",
  Daniel: "Daniel",
  Hosea: "Hosea",
  Joel: "Yoel",
  Amos: "Amos",
  Obadiah: "Obaja",
  Jonah: "Yunus",
  Micah: "Mikha",
  Nahum: "Nahum",
  Habakkuk: "Habakuk",
  Zephaniah: "Zefanya",
  Haggai: "Hagai",
  Zechariah: "Zakharia",
  Malachi: "Maleakhi",
  Matthew: "Matius",
  Mark: "Markus",
  Luke: "Lukas",
  John: "Yohanes",
  Acts: "Kisah Para Rasul",
  Romans: "Roma",
  "1 Corinthians": "1 Korintus",
  "2 Corinthians": "2 Korintus",
  Galatians: "Galatia",
  Ephesians: "Efesus",
  Philippians: "Filipi",
  Colossians: "Kolose",
  "1 Thessalonians": "1 Tesalonika",
  "2 Thessalonians": "2 Tesalonika",
  "1 Timothy": "1 Timotius",
  "2 Timothy": "2 Timotius",
  Titus: "Titus",
  Philemon: "Filemon",
  Hebrews: "Ibrani",
  James: "Yakobus",
  "1 Peter": "1 Petrus",
  "2 Peter": "2 Petrus",
  "1 John": "1 Yohanes",
  "2 John": "2 Yohanes",
  "3 John": "3 Yohanes",
  Jude: "Yudas",
  Revelation: "Wahyu",
};

export function bookDisplayName(bookEn: string, locale: Locale): string {
  if (locale === "id") {
    return BOOK_NAME_ID[bookEn] ?? bookEn;
  }
  return bookEn;
}
